### ISSUE TITLE
[FEAT] Block ALL corporate blogs

### ISSUE THREAD

**Issue by stdbug** [Drag13/HabrSanitizer#19]
Would it be useful to add an option of blocking all corporate blogs so that a user will not be forced to create a long list of spammy corp accounts?

**Comment by Drag13** [comment]
Hi @codeschlosser 

The idea is not new, but I am not sure about it. The main concern is that if you enable it - you will not able to see posts from the new blogs that might be good. 

What do you think?

**Comment by stdbug** [comment]
After a while I think that you're right, there are actually non-graphomaniac companies with really good articles. Hence, closing the issue

**Comment by Drag13** [comment]
We might back to this discussion if we get an option to show posts based on the rating. As an example: you block all my posts except that are higher than 50 or something like this.
